version: "3.7"
services:

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:6.2.0
    ports:
      - "8081:8081"
    volumes:
      - "./distribution/docker/artifactory:/var/opt/jfrog/artifactory"
